# -*- coding: utf-8 -*-
"""Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1obpai96EhDLs1SatpJSHahLDZhq3EXyT
"""

import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
import os
import pandas as pd

st.set_page_config(
    page_title="Air Quality Dashboard",
    layout="wide"
)

sns.set_style("darkgrid")

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# =====================================================
# CONFIG
# =====================================================

st.set_page_config(
    page_title="Air Quality Dashboard",
    layout="wide"
)

sns.set_style("darkgrid")

# =====================================================
# LOAD DATA
# =====================================================

df1 = pd.read_csv("data/PRSA_Data_Aotizhongxin_20130301-20170228.csv")
df2 = pd.read_csv("data/PRSA_Data_Changping_20130301-20170228.csv")
df3 = pd.read_csv("data/PRSA_Data_Dingling_20130301-20170228.csv")
df4 = pd.read_csv("data/PRSA_Data_Dongsi_20130301-20170228.csv")
df5 = pd.read_csv("data/PRSA_Data_Guanyuan_20130301-20170228.csv")
df6 = pd.read_csv("data/PRSA_Data_Gucheng_20130301-20170228.csv")
df7 = pd.read_csv("data/PRSA_Data_Huairou_20130301-20170228.csv")
df8 = pd.read_csv("data/PRSA_Data_Nongzhanguan_20130301-20170228.csv")
df9 = pd.read_csv("data/PRSA_Data_Shunyi_20130301-20170228.csv")
df10 = pd.read_csv("data/PRSA_Data_Tiantan_20130301-20170228.csv")
df11 = pd.read_csv("data/PRSA_Data_Wanliu_20130301-20170228.csv")
df12 = pd.read_csv("data/PRSA_Data_Wanshouxigong_20130301-20170228.csv")

all_df = pd.concat([
    df1, df2, df3, df4, df5, df6,
    df7, df8, df9, df10, df11, df12
], ignore_index=True)

# membuat kolom datetime
all_df["datetime"] = pd.to_datetime(
    all_df[["year", "month", "day", "hour"]]
)

# =====================================================
# SIDEBAR
# =====================================================

st.sidebar.title("Air Quality Dashboard")
st.sidebar.write("12 Monitoring Stations")

min_date = all_df["datetime"].min().date()
max_date = all_df["datetime"].max().date()

start_date, end_date = st.sidebar.date_input(
    "Pilih Rentang Tanggal",
    [min_date, max_date]
)

# =====================================================
# FILTER DATA
# =====================================================

main_df = all_df[
    (all_df["datetime"].dt.date >= start_date) &
    (all_df["datetime"].dt.date <= end_date)
]

# jika filter kosong
if main_df.empty:
    st.warning("Tidak ada data pada rentang tanggal tersebut.")
    st.stop()

# =====================================================
# HEADER
# =====================================================

st.title("Air Quality Dashboard")
st.subheader("12 Monitoring Stations")

st.write(
    """
    Dashboard ini menampilkan analisis kualitas udara
    dari 12 stasiun monitoring selama periode 2013–2017.
    """
)

# =====================================================
# METRIC
# =====================================================

col1, col2 = st.columns(2)

with col1:
    st.metric(
        "Average PM2.5",
        round(main_df["PM2.5"].mean(), 2)
    )

with col2:
    st.metric(
        "Average PM10",
        round(main_df["PM10"].mean(), 2)
    )

# =====================================================
# VISUALISASI 1
# RATA-RATA PM2.5 PER BULAN
# =====================================================

monthly_df = main_df.groupby("month").agg({
    "PM2.5": "mean"
}).reset_index()

fig, ax = plt.subplots(figsize=(10,5))

ax.plot(
    monthly_df["month"],
    monthly_df["PM2.5"],
    marker="o",
    linewidth=2
)

ax.set_title("Average PM2.5 per Month")
ax.set_xlabel("Month")
ax.set_ylabel("PM2.5")

st.pyplot(fig)

# =====================================================
# VISUALISASI 2
# PM2.5 BERDASARKAN ARAH ANGIN
# =====================================================

wind_df = main_df.groupby("wd").agg({
    "PM2.5": "mean"
}).reset_index()

fig, ax = plt.subplots(figsize=(10,5))

sns.barplot(
    data=wind_df,
    x="wd",
    y="PM2.5",
    hue="wd",
    palette="Blues",
    legend=False,
    ax=ax
)

ax.set_title("Average PM2.5 by Wind Direction")
ax.set_xlabel("Wind Direction")
ax.set_ylabel("PM2.5")

st.pyplot(fig)

# =====================================================
# VISUALISASI 3
# PM2.5 BERDASARKAN JAM
# =====================================================

hourly_df = main_df.groupby("hour").agg({
    "PM2.5": "mean"
}).reset_index()

fig, ax = plt.subplots(figsize=(10,5))

ax.plot(
    hourly_df["hour"],
    hourly_df["PM2.5"],
    marker="o",
    linewidth=2
)

ax.set_title("Average PM2.5 by Hour")
ax.set_xlabel("Hour")
ax.set_ylabel("PM2.5")

st.pyplot(fig)

# =====================================================
# TOTAL DATA
# =====================================================

st.write("Jumlah Data Setelah Filter:", len(main_df))
